/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package ru.xdsoft.fips.intranet.portal.filetree.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Folder service. Represents a row in the &quot;FT_Folder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>ru.xdsoft.fips.intranet.portal.filetree.model.impl.FolderModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>ru.xdsoft.fips.intranet.portal.filetree.model.impl.FolderImpl</code>.
 * </p>
 *
 * @author Vasiliy Platonov
 * @see Folder
 * @generated
 */
@ProviderType
public interface FolderModel extends BaseModel<Folder>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a folder model instance should use the {@link Folder} interface instead.
	 */

	/**
	 * Returns the primary key of this folder.
	 *
	 * @return the primary key of this folder
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this folder.
	 *
	 * @param primaryKey the primary key of this folder
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this folder.
	 *
	 * @return the uuid of this folder
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this folder.
	 *
	 * @param uuid the uuid of this folder
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this folder.
	 *
	 * @return the ID of this folder
	 */
	public long getId();

	/**
	 * Sets the ID of this folder.
	 *
	 * @param id the ID of this folder
	 */
	public void setId(long id);

	/**
	 * Returns the name of this folder.
	 *
	 * @return the name of this folder
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this folder.
	 *
	 * @param name the name of this folder
	 */
	public void setName(String name);

	/**
	 * Returns the parent ID of this folder.
	 *
	 * @return the parent ID of this folder
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this folder.
	 *
	 * @param parentId the parent ID of this folder
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the group ID of this folder.
	 *
	 * @return the group ID of this folder
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this folder.
	 *
	 * @param groupId the group ID of this folder
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this folder.
	 *
	 * @return the company ID of this folder
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this folder.
	 *
	 * @param companyId the company ID of this folder
	 */
	@Override
	public void setCompanyId(long companyId);

}